name: Tagger for b

on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: b
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tagger
        run: |
          git tag ${{ github.head_ref }}
          git push origin ${{ github.head_ref }}
