name: Tagger for b

on:
  workflow_dispatch:
    inputs:
      version:
        description: specify the value with format v*
        required: true
        type: string

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tagger
        run: |
          tag_name="$(git branch --show-current)"-"${{ inputs.version }}"
          git tag "$tag_name"
          git push origin "$tag_name"
