name: Tagger for b

on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: b
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tagger
        run: |
          tag_name="$(git branch --show-current)"
          git tag "$tag_name"
          git push origin "$tag_name"
