name: Tagger for b

on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: b
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tagger
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          git tag "$branch_name"
          git push origin "$branch_name"
